//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishMarket.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutCategory
    {
        public int AboutID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Parentcate { get; set; }
        public string Contents { get; set; }
    }
}
