//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishMarket.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int BannerID { get; set; }
        public string BannerPath { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> isBigBanner { get; set; }
        public Nullable<bool> isSmallBanner { get; set; }
    }
}
