//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishMarket.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public int UserID { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CommentParentId { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string IPUser { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsUserAdmin { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
