//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishMarket.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SakyMartEntities : DbContext
    {
        public SakyMartEntities()
            : base("name=SakyMartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutCategory> AboutCategories { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<dqtvf_users> dqtvf_users { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<LabelProduct> LabelProducts { get; set; }
        public virtual DbSet<ListEmail> ListEmails { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<ProductColor> ProductColors { get; set; }
        public virtual DbSet<ProductDisCount> ProductDisCounts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSize> ProductSizes { get; set; }
        public virtual DbSet<ProductVariant> ProductVariants { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<Provice> Provices { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SendEmail> SendEmails { get; set; }
        public virtual DbSet<Ship> Ships { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<SubEmail> SubEmails { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupportOnline> SupportOnlines { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_origin> tbl_origin { get; set; }
        public virtual DbSet<tbl_TypeCategories> tbl_TypeCategories { get; set; }
        public virtual DbSet<TypeDeal> TypeDeals { get; set; }
        public virtual DbSet<TypeVoucher> TypeVouchers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersInRole> UsersInRoles { get; set; }
        public virtual DbSet<VoteRating> VoteRatings { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
    }
}
