//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishMarket.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        public int ProductVariantId { get; set; }
        public string Capacity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> OldPrice { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
