//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishMarket.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendEmail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Emailfrom { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Passmail { get; set; }
        public string Servermail { get; set; }
        public Nullable<int> Port { get; set; }
    }
}
